

const LOCAL_AUTH_KEY=process.env.LOCAL_AUTH_KEY 
const DEMO_CREDENTIALS_EMAIL=process.env.DEMO_CREDENTIALS_EMAIL 
const DEMO_CREDENTIALS_EMAIL_PASSWORD=process.env.DEMO_CREDENTIALS_EMAIL_PASSWORD





export const configs = {    
    LOCAL_AUTH_KEY: LOCAL_AUTH_KEY || "local-auth",
    DEMO_CREDENTIALS_EMAIL: DEMO_CREDENTIALS_EMAIL || "",
    DEMO_CREDENTIALS_EMAIL_PASSWORD: DEMO_CREDENTIALS_EMAIL_PASSWORD || ""
}